# Generated by Django 4.1.1 on 2022-09-12 18:09

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kateqoriyamodel',
            options={'verbose_name_plural': 'Kateqoriyalar'},
        ),
        migrations.AlterField(
            model_name='kateqoriyamodel',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='ad', unique=True),
        ),
    ]
