# Generated by Django 4.1.1 on 2022-09-12 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_alter_kateqoriyamodel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='YaziModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basliq', models.CharField(blank=True, max_length=50, null=True)),
                ('sekil', models.ImageField(upload_to='yazi_sekilleri')),
                ('meqale', models.TextField()),
                ('yaradilma_tarix', models.DateTimeField(auto_now_add=True)),
                ('deyisdirilme_tarixi', models.DateField(auto_now=True)),
                ('kateqoriyalar', models.ManyToManyField(related_name='yazi', to='blog.kateqoriyamodel')),
                ('yazar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yazilar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Yazi',
                'verbose_name_plural': 'Yazilar',
                'db_table': 'Yazi',
            },
        ),
    ]
