# Generated by Django 4.1.1 on 2022-09-12 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_yazimodels'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YaziModels',
        ),
    ]
