# Generated by Django 4.1.1 on 2022-09-12 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_yazimodels'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yazimodels',
            options={'verbose_name': 'Yazi', 'verbose_name_plural': 'Yazi'},
        ),
        migrations.AlterModelTable(
            name='yazimodels',
            table='Yazi',
        ),
    ]
