# Generated by Django 4.1.1 on 2022-09-15 19:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_yazimodels_options_alter_yazimodels_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yazimodels',
            name='meqale',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
