# Generated by Django 4.1.1 on 2022-09-15 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0008_yorummodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yorummodel',
            name='yazan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yorum', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='yorummodel',
            name='yazi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yorumlar', to='blog.yazimodels'),
        ),
    ]
