# Generated by Django 4.1.1 on 2022-09-18 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_yorummodel_yazan_alter_yorummodel_yazi'),
    ]

    operations = [
        migrations.CreateModel(
            name='IletisimModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=250)),
                ('ad_soyad', models.CharField(max_length=150)),
                ('yorum', models.TextField()),
                ('yaradilma_tarixi', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'İletişim',
                'db_table': 'iletisim',
            },
        ),
    ]
